
-- Insertamos los datos de la tabla de encuestas
INSERT INTO encuestas VALUES 
('E1', 'Riesgo de Personal', 'Riesgos Operativos derivados de violaciones intencionales de las normativas internas o de las leyes por parte del personal interno; fallas en la Administración o gerencia del RRHH; omisiones en el cumplimiento de las relaciones contractuales con los empleados; etc.'),
('E2', 'Riesgo de Procesos', 'Riesgos Operativos generados por fallas en la ejecución de los procesos; deficiencias o ausencias en las políticas, normativas internas o procedimientos; fallas en la disposición de recursos, entre otros.'),
('E3', 'Riesgo de Sistemas', 'Riesgos Operativos derivados de fallas en los Sistemas Bancarios, Aplicaciones, Herramientas y elementos informáticos que utiliza la institución.'),
('E4', 'Riesgo de Factores Externos', 'Riesgos Operativos generados por acciones mal intencionadas de terceras personas; eventos naturales o de interrupciones importantes en los servicios externos.'),
('E5', 'Riesgo Reputacional y Legal', 'Riesgos derivados de operaciones vinculadas con la legitimación de capitales o financiamiento al terrorismo; fallas en la atención a clientes; de violaciones o incumplimientos de contratos, normativas o leyes que de manera no intencionada, pueda cometerse en perjuicio de terceros relacionados.');

-- Insertamos los datos de la tabla de categorias
INSERT INTO categorias VALUES
('C1', 'Captación y Capacitación de Personal', 'E1'), 
('C2', 'Gerencia de Personal', 'E1'), 
('C3', 'Coordinación del Personal', 'E1'),
('C4', 'Ética y Moral del Personal', 'E1'), 
('C5', 'Ejecución Indebida de Operaciones', 'E1'), 
('C6', 'Manejo de Información Confidencial', 'E1'),
('C7', 'Prácticas Laborales', 'E1'), 
('C8', 'Puesta en Marcha de Nuevos Productos y Servicios', 'E2'),
('C9', 'Errores, Omisiones o Retardos', 'E2'), 
('C10', 'Evaluación de Operaciones y Procesos', 'E2'), 
('C11', 'Control y Acceso a la Contabilidad', 'E2'), 
('C12', 'Verificación, Soporte y Documentación de las Operaciones', 'E2'),
('C13', 'Elaboración de Presupuestos y Definición de Límites Operativos', 'E2'), 
('C14', 'Recursos e Información Necesaria para Operar', 'E2'),
('C15', 'Planificación y Control de Gestión', 'E2'), 
('C16', 'Control y Autorización de Operaciones y Procesos', 'E2'),
('C17', 'Difusión de Normas, Decisiones y Políticas', 'E2'), 
('C18', 'Documentación de Normas y Procedimientos', 'E2'),
('C19', 'Equipos de Computación', 'E3'), 
('C20', 'Seguridad de Activos de Información', 'E3'), 
('C21', 'Aplicaciones y Programas', 'E3'),
('C22', 'Telecomunicaciones y Redes', 'E3'), 
('C23', 'Planes de Contingencia', 'E3'), 
('C24', 'Internet-Intranet', 'E3'),
('C25', 'Condición Física de las Instalaciones', 'E4'), 
('C26', 'Protección de las Instalaciones', 'E4'),
('C27', 'Servicios Outsourcing / Proveedores', 'E4'), 
('C28', 'Conocimiento del Cliente', 'E5'), 
('C29', 'Deberes con los Clientes', 'E5'), 
('C30', 'Relación con los Proveedores', 'E5'), 
('C31', 'Relación con las Contrapartes (Instituciones Financieras)', 'E5'), 
('C32', 'Relación con los Organismos y Entes de Control', 'E5');

-- Insertamos los datos de la tabla de preguntas
INSERT INTO preguntas VALUES
('R1', 'Los funcionarios de su unidad cumplen satisfactoriamente con los requerimientos de experiencia y educación formal para cada cargo.', 'C1'),
('R2', 'El entrenamiento al personal de nuevo ingreso es adecuado para los cargos asignados a su área.', 'C1'),
('R3', 'El programa de entrenamiento se ejecuta con la frecuencia necesaria para el mejoramiento del personal.', 'C1'),
('R4', 'El personal de su área está suficientemente entrenado para atender adecuadamente a los clientes internos o externos.', 'C1'),
('R5', 'Las responsabilidades y tareas del personal de su unidad están claramente establecidas y documentadas.', 'C2'),
('R6', 'Los cargos establecidos en su área son acordes a la antigüedad y experiencia de sus empleados.', 'C2'),
('R7', 'Los niveles de remuneración y bonificación al personal de su unidad son acordes con los cargos y perfiles.', 'C2'),
('R8', 'En el último año la rotación del personal en su área no ha afectado la eficiencia operativa de sus procesos.', 'C2'),
('R9', 'La antigüedad promedio de sus empleados supera los dos (2) años.', 'C3'),
('R10', 'Frecuentemente en su área se realizan reuniones de seguimiento entre los responsables de los distintos procesos.', 'C3'),
('R11', 'Las responsabilidades de su personal están acordes con las políticas de negocios y operativas establecidas a su unidad.', 'C3'),
('R12', 'En el último año no se ha transferido o retirado personal responsable de procesos críticos o de impacto operativo significativo.', 'C3'),
('R13', 'El personal de su unidad muestra una actitud responsable con la preservación de la imagen y reputación del Banco y no se ha visto incurso en actividades que las comprometan.', 'C4'),
('R14', 'En el último año en su unidad no se han presentado  eventos que pongan en duda la moral y ética del personal contratado.', 'C4'),
('R15', 'Frecuentemente los supervisores de su unidad le presentan el seguimiento que realizan de los procesos y controles establecidos en sus operaciones.', 'C5'),
('R16', 'En el último año no ha identificado eventos de excesos no documentados, en los límites establecidos para los procesos por parte del personal de su unidad.', 'C5'),
('R17', 'Los mecanismos que previenen la divulgación no autorizada de la información por parte de su personal son suficientes y adecuados.', 'C6'),
('R18', 'En el último año no ha evidenciado eventos de manejo inadecuado de la información por parte del personal asignado a su área.', 'C6'),
('R19', 'En el último año en su unidad no han ocurrido eventos de maltrato, discriminación u acoso por parte del personal supervisorio designado.', 'C7'),
('R20', 'El personal de su unidad salió de vacaciones en el último año, por lo menos en un período de 10 días hábiles consecutivos.', 'C7'),
('R21', 'En el último año en su unidad no han ocurrido eventos de paros, desacatos o reclamos laborales colectivos.', 'C7'),
('P1', 'En la reciente implantación de Productos o Servicios vinculados con su área fueron considerados para la evaluación de los procesos y riesgos operativos relacionados.', 'C8'),
('P2', 'Cuando se implanta un nuevo producto o servicio que involucra alguna de las actividades de su unidad, se documentan adecuadamente las políticas y procedimientos.', 'C8'),
('P3', 'En el último año no han ocurrido eventos de fallas en los procesos críticos de su unidad que impactaran significativamente en otros procesos críticos del Banco.', 'C9'),
('P4', 'Las fallas de procesos o errores ocurridos en su unidad han sido resueltos o corregidos con prontitud por las áreas correspondientes.', 'C9'),
('P5', 'Las actividades de su unidad son evaluadas y controladas permanentemente por los supervisores y áreas de control.', 'C10'),
('P6', 'Periódicamente, las áreas de control le reportan a Ud. las desviaciones de sus procesos y necesidad de ajustes correspondientes.', 'C10'),
('P7', 'Las cuentas contables que son afectadas por su unidad están conciliadas al cierre semestral y reflejan actualmente su naturaleza operativa.', 'C11'),
('P8', 'Los perfiles de accesos a los registros contables en su unidad, están operando adecuadamente.', 'C11'),
('P9', 'Los procesos críticos de su unidad contienen los reportes y controles suficientes para su seguimiento y auditorias.', 'C12'),
('P10', 'Las Operaciones o Transacciones ejecutadas en su unidad son periódicamente auditadas por los supervisores y unidades de control.', 'C12'),
('P11', 'Los limites operativos y presupuestos de su unidad fueron revisados y definidos adecuadamente en el último año.', 'C13'),
('P12', 'Los limites definidos para su área son debidamente auditados y controlados por otras unidades. (Auditoria, Contraloría, etc.)', 'C13'),
('P13', 'La información y recursos necesarios para realizar sus operaciones generalmente se encuentran disponibles en la oportunidad en que se requiere.', 'C14'),
('P14', 'Los reportes e información que emite o genera su unidad están generalmente disponibles para las áreas que lo requieren.', 'C14'),
('P15', 'Los Planes operativos semestrales de su unidad son evaluados y controlados periódicamente por los supervisores respectivos.', 'C15'),
('P16', 'Los proyectos relacionados con su unidad han culminado en los tiempos previstos en la planificación. ', 'C15'),
('P17', 'Los procesos críticos de su unidad disponen de suficientes controles y niveles de autorización para su ejecución.', 'C16'),
('P18', 'Los niveles de autorizaciones de los procesos y operaciones de su unidad están claramente definidos y documentados.', 'C16'),
('P19', 'Su personal conoce los lineamientos y políticas generales del Banco.', 'C17'),
('P20', 'Se encuentran a disposición del personal las normas y políticas de la Institución referidas a su área y sus procesos.', 'C17'),
('P21', 'Sus procesos están documentados adecuadamente en los manuales de normas y procedimientos del Banco.', 'C18'),
('P22', 'Los procesos críticos de su área, ajustados o modificados en el último año fueron documentados y publicados debidamente.', 'C18'),
('S1', 'Su unidad dispone de equipos de computación adecuados y suficientes para realizar sus actividades.', 'C19'),
('S2', 'Los equipos de computación que dispone su área están actualizados y generalmente no presentan fallas.', 'C19'),
('S3', 'Los sistemas y aplicaciones que utiliza en sus operaciones disponen de controles de accesos adecuados.', 'C20'),
('S4', 'Su personal aplica las Políticas de Seguridad de la Información de BOD para el uso y resguardo adecuado de los activos de información.', 'C20'),
('S5', 'El nuevo Core Bancario (IBS) ha mejorado sensiblemente los procesos y operaciones ejecutados en su unidad.', 'C21'),
('S6', 'Las Aplicaciones y programas especiales que utiliza en los procesos críticos son adecuados y responden con la eficiencia esperada.', 'C21'),
('S7', 'Las Aplicaciones y programas especiales que utiliza en los procesos críticos cuentan con los reportes y soportes necesarios para el control de las operaciones de su unidad.', 'C21'),
('S8', 'Las fallas o errores de las aplicaciones son atendidos generalmente con rapidez y eficacia por las áreas encargadas.', 'C21'),
('S9', 'La red y los servidores (correo, transacciones, etc) que utiliza en sus operaciones operan con eficiencia en los horarios regulares de operaciones.', 'C22'),
('S10', 'En su unidad se cuenta con los dispositivos de transmisión y puntos de red necesarios para los reportes de las operaciones diarias.', 'C22'),
('S11', 'Su área dispone de planes de contingencia ante fallas en los sistemas y/o aplicaciones, y están debidamente documentados.', 'C23'),
('S12', 'Los planes o medidas de contingencia ante fallas en los sistemas o aplicaciones especiales han sido probados satisfactoriamente en el último año. ', 'C23'),
('S13', 'Las actividades que realiza su área a través de la Internet o Intranet generalmente no le presentan retardos o fallas.', 'C24'),
('S14', 'Los equipos y/o aplicaciones de su unidad no han presentado fallas o problemas derivados de virus o archivos maliciosos externos.', 'C24'),
('F1', 'El espacio de trabajo de su área esta acondicionado adecuadamente, para las actividades diarias.', 'C25'),
('F2', 'El lugar de almacenamiento físico de su área es adecuado, seguro y con suficiente espacio para almacenar.', 'C25'),
('F3', 'Las instalaciones de su unidad cuentan con los medios adecuados para protegerse contra incendios, accidentes eléctricos, rotura de tuberías y otras eventualidades.', 'C25'),
('F4', 'En el espacio de trabajo de su área en el último año se han aplicado actividades correctivas o de mantenimiento preventivo para evitar el deterioro del mismo.', 'C25'),
('F5', 'Sus instalaciones cuentan con los equipos, generadores y otros elementos que suplen las fallas que pueda haber en los servicios públicos básicos (Luz, agua, teléfono,..).', 'C25'),
('F6', 'Sus instalaciones cuentan con los elementos de seguridad necesarios para protegerse contra eventos de hurtos, robos, asaltos o daños maliciosos contra la propiedad.', 'C25'),
('F7', 'Las instalaciones de su unidad disponen de personal de seguridad adecuado para la protección de las áreas físicas.', 'C26'),
('F8', 'Los controles de seguridad física que existen para el manejo de los archivos, almacenes u otros lugares para tales fines son efectivos.', 'C26'),
('F9', 'Las bóvedas y demás depósitos de seguridad cubren las exigencias mínimas para brindar protección contra terceros.', 'C26'),
('F10', 'El mantenimiento preventivo y correctivo de los elementos que brindan seguridad a las instalaciones es adecuado y constante.', 'C26'),
('F11', 'En el último año sus procesos críticos no han sido afectados por eventos de fallas en los servicios prestados por proveedores públicos o outsourcing contratados por el Banco.', 'C27'),
('F12', 'El personal de su unidad conoce los procedimientos o planes de contingencia establecidos ante fallas graves en la prestación de los servicios de parte de los proveedores o compañías outsourcing.', 'C27'),
('L1', 'La información de los clientes necesaria para sus procesos críticos esta disponible y actualizada según se requiera.', 'C28'),
('L2', 'El personal de su unidad conoce y aplica la Política de Conozca su Cliente frecuentemente.', 'C28'),
('L3', 'Su personal conoce los procedimientos de reportes de actividades sospechosas de los clientes y/o terceros.', 'C28'),
('L4', 'Los clientes que tramitan con su unidad información de sus operaciones o efectúan reclamos, obtienen la respuesta adecuada en el tiempo previsto.', 'C29'),
('L5', 'Los mecanismos o procedimientos establecidos para la presentación de reclamos de los clientes son adecuados y eficientes.', 'C29'),
('L6', 'Periódicamente en su unidad se realizan evaluaciones de la calidad del servicio prestado a los principales clientes.', 'C29'),
('L7', 'Los procedimientos de contratación con terceros establecidos por el Banco son aplicados adecuadamente en su unidad.', 'C30'),
('L8', 'Los procedimientos para celebrar contratos con los proveedores son adecuados y protegen legalmente a la Institución.', 'C30'),
('L9', 'Los procedimientos administrativos para el procesamiento de requisiciones, cancelaciones y pagos de los servicios son expeditos y controlados.', 'C30'),
('L10', 'Las operaciones o procesos con contrapartes se encuentran debidamente documentadas y verificadas por las unidades contraloras.', 'C31'),
('L11', 'En el último año no se han recibido reclamos de contrapartes sobre operaciones no conformes con lo estipulado en los contratos o convenios establecidos.', 'C31'),
('L12', 'La información de su unidad que debe ser reportada a los organismos supervisores es generada en el tiempo y con las condiciones establecidas.', 'C32'),
('L13', 'El personal de su unidad conoce las consecuencias legales y pecuniarias derivadas del incumplimiento de los deberes formales establecidos en los procesos que ejecutan.', 'C32'),
('L14', 'Su unidad conoce los procedimientos y disposiciones legales establecidas para la prevención de operaciones de legitimación de capitales y financiamiento al terrorismo.', 'C32'),
('L15', 'En el último año en su unidad no han recibido sanciones administrativas o pecuniarias derivadas del incumplimiento de las normativas referidas a sus operaciones o procesos.', 'C32');

INSERT INTO usuarios VALUES
    ('10255954', 'Roberto', 'Gonzalez', 'rjgonzalez@bod.com.ve'),
    ('29533678', 'Roger', 'Urbina', 'rurbina@bod.com.ve')